### ISSUE TITLE
For more security spongycastle -> bouncycastle

### ISSUE THREAD

**Issue by Neustradamus** [foilen/java-libraries#7]
For more security, can you change old spongycastle (based on old bouncycastle) to bouncycastle?
- https://www.bouncycastle.org/
- https://www.bouncycastle.org/releasenotes.html
- http://www.bouncycastle.org/latest_releases.html
- https://cve.mitre.org/cgi-bin/cvekey.cgi?keyword=bouncy%20castle
- https://cve.mitre.org/cgi-bin/cvekey.cgi?keyword=bouncycastle
- https://www.cvedetails.com/vulnerability-list/vendor_id-7637/Bouncycastle.html

**Comment by simonfoilen** [comment]
I removed the spongycastle library in the v3 branch

**Comment by Neustradamus** [comment]
@simonfoilen: A big thanks after 4 years of this security request!

**Comment by simonfoilen** [comment]
well you make it sound as if it took time, but it didn't:

- that v3 version without spongycastle exists since 2023-03-20 (I just didn't check the "issues" section for a while)
- the v2 version has 2 separate sub-projects: one with bouncycastle and one with spongycastle. So basically, anyone could have used the bouncycastle one if that is their preference

So in effect, that "issue" was never an issue since there was nothing to convert: both existed.

regards
